### ISSUE TITLE
Optimize transaction body

### ISSUE THREAD

**Issue by Dr-Mazen-Khaddaj** [geniusyield/atlas#205]
**Describe the bug**
When using runGYTxMonadNode, the transaction body that is constructed is including redundant output UTxOs to the user wallet, causing higher fees, and sometimes failing the transaction as a whole due to the large size.

**To Reproduce**
This is an example transaction:
https://preview.cardanoscan.io/transaction/3b74c7dba346229e9987b69801df7403c53c52ca499c7d73faa9808576a9c057?tab=utxo
as you can see 4 redundant outputs could have been only 1 output.

**Expected behavior**
Expected is a more efficient transaction, with only one change output.

**Screenshots**
![image](https://github.com/geniusyield/atlas/assets/108194995/29c12a7d-9293-4020-9f15-cb80ced1544e)

**Station (please complete the following information):**
 - OS: Ubuntu
 - Version 22.02

**Comment by TotallyNotChase** [comment]
This could be somewhat complicated since the balancing algo is designed to try and not collect all change into a single output - since that will eventually make a wallet unusable. It's a decision agreed upon on some IOG coin selection research.

I understand your concern though and maybe there should be a switch (I think there was a way to select coin selection strategy last time I checked). But in general, in the long term, it's better to _not_ make a singular change output.

**Comment by Dr-Mazen-Khaddaj** [comment]
I can't see how a single change output that has only ADA will eventually make a wallet unusable. At least there should be the option to make a compact transaction (even the option to include newly minted NFT in the change output).
I tried all coin selection strategies, but all failed. When I test using cardano-cli, everything works as intended, but with Atlas, the transaction is failing with BuildTxExUnitsTooBig.

**Comment by TotallyNotChase** [comment]
If it's not behaving the same way as cardano-wallet (and derivatives), it may indeed be a bug

**Comment by sourabhxyz** [comment]
@Dr-Mazen-Khaddaj Sorry, this issue missed my eyes. Would attempt to enable better monitoring of issues.

For your shared transaction, the last output which is having value for around ~2.44 ada is something we are trying to correct for. This reason why it gets generated is we have _fee over approximation algorithm_, that is to say, for example, we assumed fee to be 4 ada, but it actually came out to be ~1.56 ada and thus in the end we generated another change output as balance (the 2.44 ada one).

As for other three outputs, as chase mentioned earlier, some of our coin selection strategies are using cardano wallet under the hood, and the chosen algorithm their, attempts to generate change outputs same as mentioned outputs, and their are reasons to take such an approach such as to enable better concurrency (multiple available UTxOs helps in building multiple simultaneous transaction) and combat dust (selecting inputs such as to just cover required desired output and giving back small change output leads to many dust UTxOs in wallet which would later lead to increase tx size if they were to get selected).

> I can't see how a single change output that has only ADA will eventually make a wallet unusable. At least there should be the option to make a compact transaction (even the option to include newly minted NFT in the change output).

We do have a strategy which generates for one change output (besides that other one getting generated due to fee over approximation approach), namely, `GYLegacy` which should include any left over tokens.

> I tried all coin selection strategies, but all failed. When I test using cardano-cli, everything works as intended, but with Atlas, the transaction is failing with BuildTxExUnitsTooBig.

I'll try to get back to you about this as soon as I am done with some other stuff. Were you using main branch of version 0.2?

**Comment by Dr-Mazen-Khaddaj** [comment]
I'm using version 0.2. Now I copied the library and edited it to discard all change output, so now I have only 1 change output (I also tested for 1 change output, so the total becomes 2), and found that the main problem with including more inputs/outputs, is that smart contracts are consuming more memory, and that's a problem, I'm hitting the max limit of 14 million much faster, and also makes it hard to reference smart contracts to decrease fees, since referencing is increasing memory requirement. I think the transaction's success should be a priority, so maybe the logic in transaction construction should try to merge outputs in case multiple redundant outputs are causing the transaction to fail.
And also there is no support for the Masestro preview network, why? I added that to my modified one and worked fine.
