### ISSUE TITLE
add `submitTx`, `awaitTxConfirmed` to `GYTxQueryMonad`

### ISSUE THREAD

**Issue by sourabhxyz** [geniusyield/atlas#316]

**Comment by TotallyNotChase** [comment]
This would actually be very useful for something I'm working on. I almost started redesigning to implement this myself but stopped myself because that would be a bit too big of an overhaul to perform without prior communication.

Though it does make me wonder, has the work on this already started, and if so - what is the game plan?

The design I thought of essentially makes `GYTxMonadNode` a proper composable monad (and renames it to `GYTxMonadIO`). Effectively a `ReaderT` with a bunch of instances to make it composable with other stuff. And it's eval-able just like other monads. `runGYTxMonadNode` and similar are no longer tx building functions, but they are `GYTxMonadIO` evaluating functions.

I'm assuming whichever design you guys come up with would be similar, though perhaps not really worrying about the composability aspect. I only came up with that because I actually needed to compose `GYTxMonadNode` in my work and realized how awful that story currently is.

**Comment by sourabhxyz** [comment]
@TotallyNotChase We already have functions to submit the tx and await for it's confirmation as part of [`GYProviders`](https://haddock.atlas-app.io/GeniusYield-Types-Providers.html#t:GYProviders), see `gySubmitTx` and `gyAwaitTxConfirmed` inside it. Since both `GYTxQueryMonadNode` and `GYTxMonadNode` implement `GYTxQueryMonad` by making use of providers, we can easily implement new `submitTx` and `awaitTxConfirmed` members of `GYTxQueryMonad` by making use of corresponding function inside `GYProviders`. So I don't see it as a big overhaul unless I am misunderstanding something.

**Comment by sourabhxyz** [comment]
@TotallyNotChase 
We haven't started any work on this issue, but as mentioned in my previous message, I assume it to be straightforward and low-effort task.

Regarding changing underlying implementation of `GYTxMonadNode` to `ReaderT`, I am all in for it and since we don't expose the internals of   `GYTxMonadNode`, I think it won't be a breaking change (provided we leave the naming of exposed api functions/types as it is)?

**Comment by TotallyNotChase** [comment]
It's not about the availability of the providers. The issue is that `runGYTxMonadNode` and co _are built_ on the assumption that `GYTxMonadNode` does not ever modify blockchain state. Notice how the implicit typeclass laws of `GYTxMonad` make it a _contract builder_, but not a contract submitter.

**Comment by TotallyNotChase** [comment]
Of course, it still doesn't make this feature difficult to implement at all, but the changes to runGYTxMonadNode required prompt a potential (albeit not entirely necessary) redesign

**Comment by sourabhxyz** [comment]
@TotallyNotChase 
> It's not about the availability of the providers. The issue is that runGYTxMonadNode and co are built on the assumption that GYTxMonadNode does not ever modify blockchain state. Notice how the implicit typeclass laws of GYTxMonad make it a contract builder, but not a contract submitter.

I think there is a difference here. The state we are querying from can change outside our control. So even if we don't submit a transaction inside a `GYTxQueryMonad` computation, blockchain state can still be getting modified elsewhere, so personally I don't see an issue if a computation inside `GYTxQueryMonad` also submits a transaction.

I may be misunderstanding something here though.

**Comment by TotallyNotChase** [comment]
That is very true. But I was actually just referring to the API. Adding `submitTx` to the `GYTxMonad` (ideally not to `GYTxQueryMonad` since submitting is not an innocent "query", but a real modification) implies that `GYTxMonad` is now used to _submit_ transactions, not just to _build_ transactions.

But notice the type of `runGYTxMonadNode*`: `... -> GYTxMonadNode (GYTxSkeleton v) -> IO GYTxBody` (simplified version). It _expects_ `GYTxMonadNode` to only do contract building. If there is tx submission within that `GYTxMonadNode`, but the `runGYTxMonadNode*` stuff is unchanged, then you have sort of a higher order effect inside. I find that weird.

Anyway, I'm sure you'd probably end up changing the type signature of `runGYTxMonadNode*` anyway to solve that issue pretty easily. `submitTx` would only use `buildTxCore`, which is entirely under `GYTxMonadNode`, and receive `GYTxSkeleton`(s). `runGYTxMonadNode*` should then be `... -> GYTxMonadNode a -> IO a`.

The main rabbit hole is what that type signature change _could_ prompt. To me, it basically felt like now that `runGYTxMonadNode*` is a real monad interpreter, it makes sense to crave real monadic composition. I found that it requires a lot of boilerplate to compose `GYTxMonadNode` (as a base monad) with other transformers. That's the thing that would need a little redesign (which I had in mind).

Adding the `submitTx` and stuff only _prompts_ the redesign, doesn't necessarily require it. So yeah, adding it is still simple, but notice the implicit assumptions `runGYTxMonadNode` makes about the laws of `GYTxMonadNode`. I probably should've just brought up the types in the first place to clarify this, rather than talk about abstract stuff - sorry about that!

**Comment by TotallyNotChase** [comment]
I have a fleshed out design for this. It also (correlationally) makes several other components more ergonomic and lawful.
