### ISSUE TITLE
Data provider tests to test for all the functions

### ISSUE THREAD

**Issue by sourabhxyz** [geniusyield/atlas#48]
We really need to test whether we are able to successfully query information using our provider.

Thinking of golden tests over set of specified UTxOs in Preprod.

**Comment by TomasOsiecki** [comment]
Blocker: The endpoint utxosAtAddresses from Maestro is not getting all the utxos. That is why the github tests from the PR are not passing.

**Comment by 4TT1L4** [comment]
I have created an issue to add the necessary maestro config JSON in the CI build based from a GitHub repository secret:
 - https://github.com/geniusyield/atlas/issues/136

**Comment by 4TT1L4** [comment]
After having a closer look once again, it turned out that some configuration was missing. Since we are calling the [Haskell workflow](https://github.com/geniusyield/atlas/blob/main/.github/workflows/haskell.yml) from our [build workflow](https://github.com/geniusyield/atlas/blob/main/.github/workflows/build.yml), the secrets must be explicitly passed over. Without any extra configuration the secrets are not passed from the calling side. 

This has been explicitly configured on the calling side, so the secrets are passed now to the called workflow:

https://github.com/geniusyield/atlas/blob/c9275f5ca5c4767216a572c02ad92b5cafb86de8/.github/workflows/build.yml#L18-L21

On the side of the called workflow the secrets must be also explicitly declared:

https://github.com/geniusyield/atlas/blob/c9275f5ca5c4767216a572c02ad92b5cafb86de8/.github/workflows/haskell.yml#L3-L18

Now all of this is already in place and the secrets are passed properly. The tests that are using the Maestro backend could be successfully executed in the following job:

https://github.com/geniusyield/atlas/actions/runs/5247673449

**Comment by 4TT1L4** [comment]
@TomasOsiecki 
As requested, I have changed the `MAESTRO_CONFIG` secret to use the following JSON schema:

```
{
    "coreProvider": { "maestroToken" : "XXXX" },
    "networkId": "testnet-preprod",
    "logging": [{ "type": { "tag": "stderr" }, "severity": "Debug", "verbosity": "V2" }],
    "utxoCacheEnable": false
}
```

**Comment by sourabhxyz** [comment]
@4TT1L4 Thanks for it.

It seems that free tier API key is not sufficient for our use case as runs exhausted it. Let's see if it persists.

In future we can move with environment variables like so `MAESTRO_API_TOKEN=... BLOCKFROST_API_TOKEN=... cabal test atlas-tests`.
